### ISSUE TITLE
Header signatures don't work with SkyShowtime

### ISSUE THREAD

**Issue by Paco8** [Paco8/plugin.video.skyott#3]
SkyShowtime seems to be using a different key or algorithm to create header signatures, which makes the addon unusable for SkyShowtime subscribers.

Unfortunately I don't have the knowledge to find out that key. Any help about this issue would be very much appreciated by me and many other SkyShowtime subscribers.

**Comment by VCDEV1** [comment]
https://gist.github.com/xhlove/b87d36370fcd825e4a2208df0fcb8085 Take a look at this script. I think it is a frida script created for extracting the peacock hmac key. I havent tested if it is working or not but I think it will work. Also since skyshowtime is not very much different from peacock I believe this might work for it too. If you can check it out.

**Comment by Paco8** [comment]
Thank you very much for the link. I'll try to figure out how to use the script.

**Comment by TAJLN** [comment]
[peacock.log](https://github.com/Paco8/plugin.video.skyott/files/11064352/peacock.log)
The dump I got when running the script. All tokens together with account are already expired.

**Comment by Paco8** [comment]
Oh, my goodness, it works!!!
Thank you very much.
